#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ ! -f "/config/appsettings.json" ]]; then
    cp /defaults/appsettings-init.json /config/
fi

# permissions
lsiown -R abc:abc \
    /config \
    /app/kavita/wwwroot/index.html
